# 4.8 Grouping

### 0.1 Importing

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Import data
path = r"C:\Users\quinn\PycharmProjects\Instacart Basket Analysis 06-30-2021"
ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_v2.pkl'))

In [4]:
# Createing a subset 
df = ords_prods_merged[:1000000]
df.shape

(1000000, 18)

In [5]:
df.head(10)

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day
0,195.0,196,Soda,77.0,7.0,9.0,0,2539329,1,1,2,Average orders,NaN,1,0,both,Mid-range product,Regularly busy
1,14084.0,14084,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,0,2539329,1,1,2,Average orders,NaN,2,0,both,Mid-range product,Regularly busy
2,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,0,2539329,1,1,2,Average orders,NaN,3,0,both,Low-range product,Regularly busy
3,26089.0,26088,Aged White Cheddar Popcorn,23.0,19.0,4.7,0,2539329,1,1,2,Average orders,NaN,4,0,both,Low-range product,Regularly busy
4,26406.0,26405,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,0,2539329,1,1,2,Average orders,NaN,5,0,both,Low-range product,Regularly busy
5,195.0,196,Soda,77.0,7.0,9.0,1,2398795,1,2,3,Fewest orders,15.0,1,1,both,Mid-range product,Least busy
6,10258.0,10258,Pistachios,117.0,19.0,3.0,1,2398795,1,2,3,Fewest orders,15.0,2,0,both,Low-range product,Least busy
7,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,1,2398795,1,2,3,Fewest orders,15.0,3,1,both,Low-range product,Least busy
8,13176.0,13176,Bag of Organic Bananas,24.0,4.0,10.3,1,2398795,1,2,3,Fewest orders,15.0,4,0,both,Mid-range product,Least busy
9,26089.0,26088,Aged White Cheddar Popcorn,23.0,19.0,4.7,1,2398795,1,2,3,Fewest orders,15.0,5,1,both,Low-range product,Least busy

### 0.2 Grouping with pandas

This is because the output of the groupby() function isn’t visible
For that reason, you should always use the groupby() function as part of a series of steps, namely, the following:

1.Split the data into groups based on some criteria.

2.Apply a function to each group separately.

3.Combine the results into a dataframe or alternative data structure or create a new column in the current dataframe.

#### 0.2a Grouping with groupby()

In [6]:
# Just like it sounds, this function will group a given dataframe by a given column
df.groupby('product_name')

#### 0.2b Aggregating data with agg()

In [7]:
 # preforming a single aggregation takes step one and two
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.800024
2.0              17.091743
3.0              17.913544
4.0              17.893092
5.0              15.214270
6.0              15.382135
7.0              17.694027
8.0              16.458105
9.0              15.957363
10.0             20.091818
11.0             16.482026
12.0             15.615061
13.0             16.484023
14.0             17.524632
15.0             15.691875
16.0             18.014071
17.0             16.150593
18.0             19.602850
19.0             17.631340
20.0             17.138607
21.0             21.956893

In [8]:
df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.800024
2.0     17.091743
3.0     17.913544
4.0     17.893092
5.0     15.214270
6.0     15.382135
7.0     17.694027
8.0     16.458105
9.0     15.957363
10.0    20.091818
11.0    16.482026
12.0    15.615061
13.0    16.484023
14.0    17.524632
15.0    15.691875
16.0    18.014071
17.0    16.150593
18.0    19.602850
19.0    17.631340
20.0    17.138607
21.0    21.956893
Name: order_number, dtype: float64

In [10]:
# preforming multiple aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.800024   1  99
2.0              17.091743   1  98
3.0              17.913544   1  99
4.0              17.893092   1  99
5.0              15.214270   1  99
6.0              15.382135   1  99
7.0              17.694027   1  99
8.0              16.458105   1  91
9.0              15.957363   1  99
10.0             20.091818   1  99
11.0             16.482026   1  99
12.0             15.615061   1  99
13.0             16.484023   1  99
14.0             17.524632   1  99
15.0             15.691875   1  99
16.0             18.014071   1  99
17.0             16.150593   1  99
18.0             19.602850   1  99
19.0             17.631340   1  99
20.0             17.138607   1  99
21.0             21.956893   1  97

#### 0.2c aggregating data with transform()

Now, let’s map this task onto the three-step process introduced earlier:

1.Split the data into groups based on the “user_id” column.

2.Apply the transform() function on the “order_number” column to generate the maximum orders for each user.

3.Create a new column, “max_order,” into which you’ll place the results of your aggregation.

In [12]:
ords_prods_merged['max_order'] = ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [14]:
pd.options.display.max_rows = None
ords_prods_merged.head(100)

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,max_order
0,195.0,196,Soda,77.0,7.0,9.0,0,2539329,1,1,2,Average orders,NaN,1,0,both,Mid-range product,Regularly busy,10
1,14084.0,14084,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,0,2539329,1,1,2,Average orders,NaN,2,0,both,Mid-range product,Regularly busy,10
2,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,0,2539329,1,1,2,Average orders,NaN,3,0,both,Low-range product,Regularly busy,10
3,26089.0,26088,Aged White Cheddar Popcorn,23.0,19.0,4.7,0,2539329,1,1,2,Average orders,NaN,4,0,both,Low-range product,Regularly busy,10
4,26406.0,26405,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,0,2539329,1,1,2,Average orders,NaN,5,0,both,Low-range product,Regularly busy,10
5,195.0,196,Soda,77.0,7.0,9.0,1,2398795,1,2,3,Fewest orders,15.0,1,1,both,Mid-range product,Least busy,10
6,10258.0,10258,Pistachios,117.0,19.0,3.0,1,2398795,1,2,3,Fewest orders,15.0,2,0,both,Low-range product,Least busy,10
7,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,1,2398795,1,2,3,Fewest orders,15.0,3,1,both,Low-range product,Least busy,10
8,13176.0,13176,Bag of Organic Bananas,24.0,4.0,10.3,1,2398795,1,2,3,Fewest orders,15.0,4,0,both,Mid-range product,Least busy,10
9,26089.0,26088,Aged White Cheddar Popcorn,23.0,19.0,4.7,1,2398795,1,2,3,Fewest orders,15.0,5,1,both,Low-range product,Least busy,10
10,13032.0,13032,Cinnamon Toast Crunch,121.0,14.0,4.0,1,2398795,1,2,3,Fewest orders,15.0,6,0,both,Low-range product,Least busy,10
11,195.0,196,Soda,77.0,7.0,9.0,2,473747,1,3,3,Fewest orders,21.0,1,1,both,Mid-range product,Least busy,10
12,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,2,473747,1,3,3,Fewest orders,21.0,2,1,both,Low-range product,Least busy,10
13,10258.0,10258,Pistachios,117.0,19.0,3.0,2,473747,1,3,3,Fewest orders,21.0,3,1,both,Low-range product,Least busy,10
14,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,2,473747,1,3,3,Fewest orders,21.0,4,0,both,Mid-range product,Least busy,10
15,30452.0,30450,Creamy Almond Butter,88.0,13.0,3.2,2,473747,1,3,3,Fewest orders,21.0,5,0,both,Low-range product,Least busy,10
16,195.0,196,Soda,77.0,7.0,9.0,3,2254736,1,4,4,Fewest orders,29.0,1,1,both,Mid-range product,Least busy,10
17,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,3,2254736,1,4,4,Fewest orders,29.0,2,1,both,Low-range product,Least busy,10
18,10258.0,10258,Pistachios,117.0,19.0,3.0,3,2254736,1,4,4,Fewest orders,29.0,3,1,both,Low-range product,Least busy,10
19,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,3,2254736,1,4,4,Fewest orders,29.0,4,1,both,Mid-range product,Least busy,10
20,26406.0,26405,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,3,2254736,1,4,4,Fewest orders,29.0,5,1,both,Low-range product,Least busy,10
21,195.0,196,Soda,77.0,7.0,9.0,4,431534,1,5,4,Fewest orders,28.0,1,1,both,Mid-range product,Least busy,10
22,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,4,431534,1,5,4,Fewest orders,28.0,2,1,both,Low-range product,Least busy,10
23,10258.0,10258,Pistachios,117.0,19.0,3.0,4,431534,1,5,4,Fewest orders,28.0,3,1,both,Low-range product,Least busy,10
24,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,4,431534,1,5,4,Fewest orders,28.0,4,1,both,Mid-range product,Least busy,10
25,10326.0,10326,Organic Fuji Apples,24.0,4.0,2.7,4,431534,1,5,4,Fewest orders,28.0,5,0,both,Low-range product,Least busy,10
26,17122.0,17122,Honeycrisp Apples,24.0,4.0,14.0,4,431534,1,5,4,Fewest orders,28.0,6,0,both,Mid-range product,Least busy,10
27,41791.0,41787,Bartlett Pears,24.0,4.0,5.0,4,431534,1,5,4,Fewest orders,28.0,7,0,both,Low-range product,Least busy,10
28,13176.0,13176,Bag of Organic Bananas,24.0,4.0,10.3,4,431534,1,5,4,Fewest orders,28.0,8,1,both,Mid-range product,Least busy,10
29,195.0,196,Soda,77.0,7.0,9.0,5,3367565,1,6,2,Average orders,19.0,1,1,both,Mid-range product,Regularly busy,10
30,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,5,3367565,1,6,2,Average orders,19.0,2,1,both,Low-range product,Regularly busy,10
31,10258.0,10258,Pistachios,117.0,19.0,3.0,5,3367565,1,6,2,Average orders,19.0,3,1,both,Low-range product,Regularly busy,10
32,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,5,3367565,1,6,2,Average orders,19.0,4,1,both,Mid-range product,Regularly busy,10
33,195.0,196,Soda,77.0,7.0,9.0,6,550135,1,7,1,Average orders,20.0,1,1,both,Mid-range product,Busiest day,10
34,10258.0,10258,Pistachios,117.0,19.0,3.0,6,550135,1,7,1,Average orders,20.0,2,1,both,Low-range product,Busiest day,10
35,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,6,550135,1,7,1,Average orders,20.0,3,1,both,Low-range product,Busiest day,10
36,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,6,550135,1,7,1,Average orders,20.0,4,1,both,Mid-range product,Busiest day,10
37,13032.0,13032,Cinnamon Toast Crunch,121.0,14.0,4.0,6,550135,1,7,1,Average orders,20.0,5,1,both,Low-range product,Busiest day,10
38,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,7,3108588,1,8,1,Average orders,14.0,1,1,both,Low-range product,Busiest day,10
39,195.0,196,Soda,77.0,7.0,9.0,7,3108588,1,8,1,Average orders,14.0,2,1,both,Mid-range product,Busiest day,10
40,10258.0,10258,Pistachios,117.0,19.0,3.0,7,3108588,1,8,1,Average orders,14.0,3,1,both,Low-range product,Busiest day,10
41,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,7,3108588,1,8,1,Average orders,14.0,4,1,both,Mid-range product,Busiest day,10
42,46153.0,46149,Zero Calorie Cola,77.0,7.0,13.4,7,3108588,1,8,1,Average orders,14.0,5,0,both,Mid-range product,Busiest day,10
43,49239.0,49235,Organic Half & Half,53.0,16.0,1.8,7,3108588,1,8,1,Average orders,14.0,6,0,both,Low-range product,Busiest day,10
44,49239.0,49235,Organic Half & Half,53.0,16.0,1.8,8,2295261,1,9,1,Average orders,0.0,1,1,both,Low-range product,Busiest day,10
45,46153.0,46149,Zero Calorie Cola,77.0,7.0,13.4,8,2295261,1,9,1,Average orders,0.0,2,1,both,Mid-range product,Busiest day,10
46,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,8,2295261,1,9,1,Average orders,0.0,3,1,both,Mid-range product,Busiest day,10
47,195.0,196,Soda,77.0,7.0,9.0,8,2295261,1,9,1,Average orders,0.0,4,1,both,Mid-range product,Busiest day,10
48,10258.0,10258,Pistachios,117.0,19.0,3.0,8,2295261,1,9,1,Average orders,0.0,5,1,both,Low-range product,Busiest day,10
49,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,8,2295261,1,9,1,Average orders,0.0,6,1,both,Low-range product,Busiest day,10
50,195.0,196,Soda,77.0,7.0,9.0,9,2550362,1,10,4,Fewest orders,30.0,1,1,both,Mid-range product,Least busy,10
51,46153.0,46149,Zero Calorie Cola,77.0,7.0,13.4,9,2550362,1,10,4,Fewest orders,30.0,2,1,both,Mid-range product,Least busy,10
52,39661.0,39657,Milk Chocolate Almonds,45.0,19.0,6.8,9,2550362,1,10,4,Fewest orders,30.0,3,0,both,Mid-range product,Least busy,10
53,38932.0,38928,0% Greek Strained Yogurt,120.0,16.0,12.6,9,2550362,1,10,4,Fewest orders,30.0,4,0,both,Mid-range product,Least busy,10
54,25134.0,25133,Organic String Cheese,21.0,16.0,8.6,9,2550362,1,10,4,Fewest orders,30.0,5,1,both,Mid-range product,Least busy,10
55,10258.0,10258,Pistachios,117.0,19.0,3.0,9,2550362,1,10,4,Fewest orders,30.0,6,1,both,Low-range product,Least busy,10
56,35955.0,35951,Organic Unsweetened Almond Milk,91.0,16.0,1.3,9,2550362,1,10,4,Fewest orders,30.0,7,0,both,Low-range product,Least busy,10
57,13032.0,13032,Cinnamon Toast Crunch,121.0,14.0,4.0,9,2550362,1,10,4,Fewest orders,30.0,8,1,both,Low-range product,Least busy,10
58,12427.0,12427,Original Beef Jerky,23.0,19.0,4.4,9,2550362,1,10,4,Fewest orders,30.0,9,1,both,Low-range product,Least busy,10
59,32794.0,32792,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,11,2168274,2,1,2,Average orders,NaN,1,0,both,Mid-range product,Regularly busy,14
60,47770.0,47766,Organic Avocado,24.0,4.0,6.3,11,2168274,2,1,2,Average orders,NaN,2,0,both,Mid-range product,Regularly busy,14
61,20575.0,20574,Roasted Turkey,96.0,20.0,2.3,11,2168274,2,1,2,Average orders,NaN,3,0,both,Low-range product,Regularly busy,14
62,12000.0,12000,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,11,2168274,2,1,2,Average orders,NaN,4,0,both,Mid-range product,Regularly busy,14
63,48114.0,48110,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,11,2168274,2,1,2,Average orders,NaN,5,0,both,Low-range product,Regularly busy,14
64,22475.0,22474,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,11,2168274,2,1,2,Average orders,NaN,6,0,both,Low-range product,Regularly busy,14
65,16589.0,16589,Plantain Chips,107.0,19.0,5.0,11,2168274,2,1,2,Average orders,NaN,7,0,both,Low-range product,Regularly busy,14
66,35921.0,35917,Organic Just Concord Grape Juice,98.0,7.0,9.4,11,2168274,2,1,2,Average orders,NaN,8,0,both,Mid-range product,Regularly busy,14
67,27346.0,27344,Uncured Genoa Salami,96.0,20.0,14.8,11,2168274,2,1,2,Average orders,NaN,9,0,both,Mid-range product,Regularly busy,14
68,30491.0,30489,Original Hummus,67.0,20.0,7.5,11,2168274,2,1,2,Average orders,NaN,10,0,both,Mid-range product,Regularly busy,14
69,27968.0,27966,Organic Raspberries,123.0,4.0,4.4,11,2168274,2,1,2,Average orders,NaN,11,0,both,Low-range product,Regularly busy,14
70,13176.0,13176,Bag of Organic Bananas,24.0,4.0,10.3,11,2168274,2,1,2,Average orders,NaN,12,0,both,Mid-range product,Regularly busy,14
71,45070.0,45066,Honeycrisp Apple,24.0,4.0,2.5,11,2168274,2,1,2,Average orders,NaN,13,0,both,Low-range product,Regularly busy,14
72,16797.0,16797,Strawberries,24.0,4.0,1.3,12,1501582,2,2,5,Average orders,10.0,1,0,both,Low-range product,Regularly busy,14
73,47530.0,47526,Goat Cheese Log,21.0,16.0,2.0,12,1501582,2,2,5,Average orders,10.0,2,0,both,Low-range product,Regularly busy,14
74,8479.0,8479,Original Black Box Tablewater Cracker,78.0,19.0,3.5,12,1501582,2,2,5,Average orders,10.0,3,0,both,Low-range product,Regularly busy,14
75,47770.0,47766,Organic Avocado,24.0,4.0,6.3,12,1501582,2,2,5,Average orders,10.0,4,1,both,Mid-range product,Regularly busy,14
76,19052.0,19051,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,12,1501582,2,2,5,Average orders,10.0,5,0,both,Low-range product,Regularly busy,14
77,8138.0,8138,Traditional Hummus,67.0,20.0,2.0,12,1501582,2,2,5,Average orders,10.0,6,0,both,Low-range product,Regularly busy,14
78,47770.0,47766,Organic Avocado,24.0,4.0,6.3,13,1901567,2,3,1,Average orders,3.0,1,1,both,Mid-range product,Busiest day,14
79,32794.0,32792,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,13,1901567,2,3,1,Average orders,3.0,2,1,both,Mid-range product,Busiest day,14
80,20575.0,20574,Roasted Turkey,96.0,20.0,2.3,13,1901567,2,3,1,Average orders,3.0,3,1,both,Low-range product,Busiest day,14
81,7781.0,7781,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,13,1901567,2,3,1,Average orders,3.0,4,0,both,Mid-range product,Busiest day,14
82,28876.0,28874,Carrot Ginger Soup,1.0,20.0,6.2,13,1901567,2,3,1,Average orders,3.0,5,0,both,Mid-range product,Busiest day,14
83,49455.0,49451,Artichoke Spinach Dip,67.0,20.0,7.1,14,738281,2,4,2,Average orders,8.0,1,0,both,Mid-range product,Regularly busy,14
84,32794.0,32792,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,14,738281,2,4,2,Average orders,8.0,2,1,both,Mid-range product,Regularly busy,14
85,32141.0,32139,Hommus Classic Original,67.0,20.0,7.5,14,738281,2,4,2,Average orders,8.0,3,0,both,Mid-range product,Regularly busy,14
86,34690.0,34688,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,14,738281,2,4,2,Average orders,8.0,4,0,both,Mid-range product,Regularly busy,14
87,36739.0,36735,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,14,738281,2,4,2,Average orders,8.0,5,0,both,Mid-range product,Regularly busy,14
88,37650.0,37646,Organic Gala Apples,24.0,4.0,9.1,14,738281,2,4,2,Average orders,8.0,6,0,both,Mid-range product,Regularly busy,14
89,22830.0,22829,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,14,738281,2,4,2,Average orders,8.0,7,0,both,Mid-range product,Regularly busy,14
90,24853.0,24852,Banana,24.0,4.0,12.3,14,738281,2,4,2,Average orders,8.0,8,0,both,Mid-range product,Regularly busy,14
91,47213.0,47209,Organic Hass Avocado,24.0,4.0,4.0,14,738281,2,4,2,Average orders,8.0,9,0,both,Low-range product,Regularly busy,14
92,33278.0,33276,Kalamata Olive Spread,67.0,20.0,10.8,14,738281,2,4,2,Average orders,8.0,10,0,both,Mid-range product,Regularly busy,14
93,45617.0,45613,Pad Thai,38.0,1.0,12.6,14,738281,2,4,2,Average orders,8.0,11,0,both,Mid-range product,Regularly busy,14
94,9681.0,9681,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,14,738281,2,4,2,Average orders,8.0,12,0,both,Low-range product,Regularly busy,14
95,21151.0,21150,Fire Grilled Steak Bowl,38.0,1.0,5.9,14,738281,2,4,2,Average orders,8.0,13,0,both,Mid-range product,Regularly busy,14
96,47148.0,47144,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,15,1673511,2,5,3,Fewest orders,8.0,1,0,both,Mid-range product,Least busy,14
97,5322.0,5322,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,15,1673511,2,5,3,Fewest orders,8.0,2,0,both,Low-range product,Least busy,14
98,17224.0,17224,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,15,1673511,2,5,3,Fewest orders,8.0,3,0,both,Low-range product,Least busy,14
99,38660.0,38656,Gluten Free Peanut Butter Dark Chocolate Chewy...,3.0,19.0,3.4,15,1673511,2,5,3,Fewest orders,8.0,4,0,both,Low-range product,Least busy,14

In [15]:
ords_prods_merged.loc[ords_prods_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
ords_prods_merged.loc[(ords_prods_merged['max_order'] <= 40) & (ords_prods_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
ords_prods_merged.loc[ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
ords_prods_merged['loyalty_flag'].value_counts(dropna=False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [20]:
ords_prods_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1